#!/bin/bash

# The output directory is the first argument
OUTPUT_DIR=$(readlink -f "$1")

function write_source_line {
    if [ -e "$1" ]; then
        # Edit the user's .bashrc file 
        SOURCE_LINE="source $(readlink -f $2)"
        grep "$SOURCE_LINE" "$1" > /dev/null 2>&1
        if [ $? != 0 ]; then
            echo $SOURCE_LINE >> $1
        fi
    fi
}

# Jump to the directory that holds this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR >& /dev/null

SCRIPT_PATH=$(readlink -f $0)
ENV_VAR_FILE=$(readlink -f "${OUTPUT_DIR}/setenv.sh")

# Create the setenv.sh file
echo "#!/bin/bash" > ${ENV_VAR_FILE}
echo "######################################################" >> ${ENV_VAR_FILE}
echo "# DO NOT EDIT. Generated by: " >> ${ENV_VAR_FILE}
echo "# ${SCRIPT_PATH}" >> ${ENV_VAR_FILE}
echo "######################################################" >> ${ENV_VAR_FILE}

export ROOT=$(readlink -f "../")
echo 'export SCRIMMAGE_PLUGIN_PATH=${SCRIMMAGE_PLUGIN_PATH}:'"${ROOT}/plugin_libs:${ROOT}/plugins" >> ${ENV_VAR_FILE}

if [ -e "${ROOT}/data" ]; then
    echo 'export SCRIMMAGE_DATA_PATH=${SCRIMMAGE_DATA_PATH}:'"${ROOT}/data" >> ${ENV_VAR_FILE}
fi

echo 'export PATH=${PATH}:'${ROOT}'/bin' >> ${ENV_VAR_FILE}
echo 'export PATH=${PATH}:'${ROOT}'/lib' >> ${ENV_VAR_FILE}
echo 'export PYTHONPATH=${PYTHONPATH}:'${ROOT}'/plugins/autonomy/python' >> ${ENV_VAR_FILE}
echo "export SCRIMMAGE_TACTIC_INTERFACE_FILE=${ROOT}/plugins/autonomy/python/behaviors.xml" >> ${ENV_VAR_FILE}

chmod +x ${ENV_VAR_FILE}
source $ENV_VAR_FILE

write_source_line "${HOME}/.bashrc" "$ENV_VAR_FILE"
write_source_line "${HOME}/.zshrc" "$ENV_VAR_FILE"

popd >& /dev/null
