#!/bin/bash
# ---------------------------------------------------------------------------
# @section LICENSE
#  
# Copyright (c) 2016 Georgia Tech Research Institute (GTRI) 
#               All Rights Reserved
#  
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.
# ---------------------------------------------------------------------------
# @file filename.ext
# @author Kevin DeMarco <kevin.demarco@gtri.gatech.edu> 
# @author Eric Squires <eric.squires@gtri.gatech.edu>
# @version 1.0
# ---------------------------------------------------------------------------
# @brief A brief description.
# 
# @section DESCRIPTION
# A long description.
# ---------------------------------------------------------------------------

# The output directory is the first argument
OUTPUT_DIR=$(readlink -f "$1")

function write_source_line {
    if [ -e "$1" ]; then
        # Edit the user's .bashrc file 
        SOURCE_LINE="source $(readlink -f $2)"
        grep "$SOURCE_LINE" "$1" > /dev/null 2>&1
        if [ $? != 0 ]; then
            echo $SOURCE_LINE >> $1
        fi
    fi
}

# Jump to the directory that holds this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR >& /dev/null

SCRIPT_PATH=$(readlink -f $0)
ENV_VAR_FILE=$(readlink -f "${OUTPUT_DIR}/setenv.sh")

# Create the setenv.sh file
echo "#!/bin/bash" > ${ENV_VAR_FILE}
echo "######################################################" >> ${ENV_VAR_FILE}
echo "# DO NOT EDIT. Generated by: " >> ${ENV_VAR_FILE}
echo "# ${SCRIPT_PATH}" >> ${ENV_VAR_FILE}
echo "######################################################" >> ${ENV_VAR_FILE}

export SCRIMMAGE_ROOT=$(readlink -f "../")

#echo 'export SCRIMMAGE_ROOT='${SCRIMMAGE_ROOT} >> ${ENV_VAR_FILE}
echo 'export SCRIMMAGE_BUILD='${OUTPUT_DIR} >> ${ENV_VAR_FILE}
echo 'export SCRIMMAGE_PLUGIN_PATH=${SCRIMMAGE_PLUGIN_PATH}:'${SCRIMMAGE_ROOT}/plugin_libs:${SCRIMMAGE_ROOT}/plugins >> ${ENV_VAR_FILE}
echo 'export SCRIMMAGE_CONFIG_PATH=${SCRIMMAGE_CONFIG_PATH}:'${SCRIMMAGE_ROOT}/config >> ${ENV_VAR_FILE}
echo 'export SCRIMMAGE_DATA_PATH=${SCRIMMAGE_DATA_PATH}:'${SCRIMMAGE_ROOT}/data >> ${ENV_VAR_FILE}
echo "export JSBSIM_ROOT=${SCRIMMAGE_ROOT}/build/3rd-party/src/jsbsim" >> ${ENV_VAR_FILE}
echo "export TINYDNN_ROOT=${SCRIMMAGE_ROOT}/build/3rd-party/src/tiny-dnn" >> ${ENV_VAR_FILE}
echo 'export PATH=${PATH}:'${SCRIMMAGE_ROOT}'/bin:'${SCRIMMAGE_ROOT}'/build/3rd-party/bin:'${SCRIMMAGE_ROOT}'/scripts' >> ${ENV_VAR_FILE}
echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:'${SCRIMMAGE_ROOT}'/build/3rd-party/lib:'${SCRIMMAGE_ROOT}'/msg_libs' >> ${ENV_VAR_FILE}

# TODO: Try to get rid of these also.
echo 'export PYTHONPATH=${PYTHONPATH}:'${SCRIMMAGE_ROOT}'/plugins/autonomy/python' >> ${ENV_VAR_FILE}
echo 'export PYTHONPATH=${PYTHONPATH}:'${SCRIMMAGE_ROOT}'/build/plugins/msg' >> ${ENV_VAR_FILE} 

chmod +x ${ENV_VAR_FILE}
source $ENV_VAR_FILE

write_source_line "${HOME}/.bashrc" "$ENV_VAR_FILE"
write_source_line "${HOME}/.zshrc" "$ENV_VAR_FILE"

popd >& /dev/null
